<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <InvariantGlobalization>false</InvariantGlobalization>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Product>Ham for Windows</Product>
    <Company>Ham</Company>
    <Version>1.0.0</Version>
    <NeutralLanguage>zh-Hans</NeutralLanguage>
  </PropertyGroup>

</Project>
