<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Ham.Infrastructure</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2957.106" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ham.Core\Ham.Core.csproj" />
  </ItemGroup>

</Project>
